language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


before_script:
 # - npm install -g gulp
  - npm install hexo-abbrlink --save
  - npm install hexo-renderer-jade --save
#  - npm install -g cnpm --registry=https://registry.npm.taobao.org
  - npm install hexo-renderer-sass --save
script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "zhezhiyong"
  - git config user.email "zhezhiyong@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF=github.com/zheng-zy/zheng-zy.github.io.git
